### ISSUE TITLE
How to use the package?

### ISSUE THREAD

**Issue by Guitaricet** [MilaNLProc/honest#1]
Thank you for making the dataset available and the package easy to install. I would like to use HONEST in my research, but there is no documentation or usage examples.

My guess would be that the main method to compute the metric is `HonestEvaluator.honest()`, but there is no explanation for what `predicted_words` format is. `tests` directory also does not include anything that could demonstrate expected usage.

**Comment by vinid** [comment]
Hello @Guitaricet!

we are still smoothing out some parts of the package and we still need to jot down proper documentation. In the meantime, you can use this [notebook](https://colab.research.google.com/drive/1mccxleNLtwLGeX0hANbjgUsrNVS6Zzvx?usp=sharing) to start playing with HONEST.

Let me know if you need further help!
